/**
 * Media Studio — Format Definitions
 *
 * All supported input/output media formats with metadata.
 */

import type { FormatInfo } from './types';

export const FORMATS: Record<string, FormatInfo> = {
  mp4: {
    id: 'mp4',
    label: 'MP4',
    type: 'video',
    extensions: ['.mp4'],
    mimeType: 'video/mp4',
    description: 'MPEG-4 Part 14 — the universal video format. Best compatibility across all platforms and devices.',
    bestFor: ['Web', 'Streaming', 'YouTube', 'Mobile', 'Social Media'],
    compatibility: 5,
    quality: 4,
    compression: 4,
    pros: ['Universal browser support', 'Good compression', 'Streaming friendly', 'Hardware accelerated decoding'],
    cons: ['No transparency support', 'Older container standard'],
    browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera'],
    useCases: ['Web video', 'YouTube uploads', 'Social media', 'Mobile playback', 'Archiving'],
  },
  mov: {
    id: 'mov',
    label: 'MOV',
    type: 'video',
    extensions: ['.mov'],
    mimeType: 'video/quicktime',
    description: 'Apple QuickTime Movie format. Industry standard for video editing and professional workflows.',
    bestFor: ['Apple Ecosystem', 'Video Editing', 'High Quality', 'Professional'],
    compatibility: 3,
    quality: 5,
    compression: 3,
    pros: ['Excellent quality', 'Editing-friendly', 'Multiple tracks', 'Apple ecosystem native'],
    cons: ['Large file sizes', 'Not streaming-friendly', 'Limited browser support'],
    browserSupport: ['Safari', 'Chrome (limited)'],
    useCases: ['Video editing', 'Apple ecosystem', 'Professional production', 'Archiving'],
  },
  avi: {
    id: 'avi',
    label: 'AVI',
    type: 'video',
    extensions: ['.avi'],
    mimeType: 'video/x-msvideo',
    description: 'Audio Video Interleave — legacy Microsoft container. Still used for older content and legacy systems.',
    bestFor: ['Legacy Systems', 'Windows Compatibility', 'Archival'],
    compatibility: 2,
    quality: 4,
    compression: 2,
    pros: ['Simple structure', 'Wide legacy support', 'No codec required for playback'],
    cons: ['Very large files', 'No streaming', 'Limited metadata support', 'Outdated'],
    browserSupport: ['None (requires plugin)'],
    useCases: ['Legacy systems', 'Windows compatibility', 'Uncompressed archival'],
  },
  mkv: {
    id: 'mkv',
    label: 'MKV',
    type: 'video',
    extensions: ['.mkv'],
    mimeType: 'video/x-matroska',
    description: 'Matroska Multimedia Container — open standard, supports unlimited tracks, chapters, and subtitles.',
    bestFor: ['Archiving', 'Multiple Audio Tracks', 'Subtitles', 'High Quality'],
    compatibility: 3,
    quality: 5,
    compression: 4,
    pros: ['Open standard', 'Multiple audio/subtitle tracks', 'Chapter support', 'Error recovery'],
    cons: ['Limited browser support', 'Larger than MP4', 'Not streaming-friendly'],
    browserSupport: ['Chrome (limited)', 'Firefox (limited)'],
    useCases: ['Video archiving', 'Multi-language content', 'High-quality storage', 'Subtitles'],
  },
  webm: {
    id: 'webm',
    label: 'WEBM',
    type: 'video',
    extensions: ['.webm'],
    mimeType: 'video/webm',
    description: 'Google\'s royalty-free web-optimized video format. Designed for the modern web.',
    bestFor: ['Web', 'Chrome', 'Firefox', 'Streaming', 'Transparency'],
    compatibility: 3,
    quality: 4,
    compression: 5,
    pros: ['Royalty-free', 'Excellent compression (VP9/AV1)', 'Transparency support', 'Web-optimized'],
    cons: ['No Safari support', 'Limited editing software support', 'Not supported by iOS'],
    browserSupport: ['Chrome', 'Firefox', 'Opera', 'Edge'],
    useCases: ['Web video', 'Chrome/Firefox optimization', 'Streaming', 'Transparent video'],
  },
  gif: {
    id: 'gif',
    label: 'GIF',
    type: 'video',
    extensions: ['.gif'],
    mimeType: 'image/gif',
    description: 'Graphics Interchange Format — classic animated image format. Universally supported but limited colors.',
    bestFor: ['Simple Animations', 'Memes', 'Social Media', 'No Audio'],
    compatibility: 5,
    quality: 2,
    compression: 1,
    pros: ['Universal support', 'No audio needed', 'Autoplay', 'Simple to share'],
    cons: ['256 color limit', 'Large file size', 'No audio', 'No modern compression'],
    browserSupport: ['All browsers'],
    useCases: ['Memes', 'Simple animations', 'Social media reactions', 'Short clips without audio'],
  },
  mp3: {
    id: 'mp3',
    label: 'MP3',
    type: 'audio',
    extensions: ['.mp3'],
    mimeType: 'audio/mpeg',
    description: 'MPEG Audio Layer III — the most widely compatible audio format. Perfect for music and podcasts.',
    bestFor: ['Music', 'Podcasts', 'Universal Playback', 'Portable Devices'],
    compatibility: 5,
    quality: 3,
    compression: 4,
    pros: ['Universal support', 'Small file size', 'Streaming-friendly', 'All devices'],
    cons: ['Lossy compression', 'Older technology', 'Lower quality than modern codecs at same bitrate'],
    browserSupport: ['All browsers'],
    useCases: ['Music distribution', 'Podcasts', 'Portable players', 'Streaming'],
  },
  wav: {
    id: 'wav',
    label: 'WAV',
    type: 'audio',
    extensions: ['.wav'],
    mimeType: 'audio/wav',
    description: 'Waveform Audio File Format — uncompressed audio with maximum quality. Best for editing and archiving.',
    bestFor: ['Audio Editing', 'Professional', 'Archiving', 'Maximum Quality'],
    compatibility: 5,
    quality: 5,
    compression: 1,
    pros: ['Lossless quality', 'Universal support', 'Editing-friendly', 'Simple structure'],
    cons: ['Very large files', 'No compression', 'No metadata by default'],
    browserSupport: ['All browsers'],
    useCases: ['Audio editing', 'Professional recording', 'Mastering', 'Archival'],
  },
  ogg: {
    id: 'ogg',
    label: 'OGG',
    type: 'audio',
    extensions: ['.ogg'],
    mimeType: 'audio/ogg',
    description: 'OGG is a free, open container format that typically contains the Vorbis audio codec. Popular in open-source applications.',
    bestFor: ['Open Source', 'Gaming', 'Streaming'],
    compatibility: 3,
    quality: 4,
    compression: 4,
    pros: ['Free/open', 'Good compression', 'Good quality'],
    cons: ['Limited device support', 'Not supported by Apple devices'],
    browserSupport: ['Chrome', 'Firefox', 'Opera', 'Edge'],
    useCases: ['Open source software', 'Gaming audio', 'Streaming'],
  },
  aac: {
    id: 'aac',
    label: 'AAC',
    type: 'audio',
    extensions: ['.aac'],
    mimeType: 'audio/aac',
    description: 'Advanced Audio Codec — the standard for YouTube, iPhone, and modern streaming. Better quality than MP3 at same bitrate.',
    bestFor: ['Streaming', 'YouTube', 'Apple Devices', 'Modern Audio'],
    compatibility: 4,
    quality: 4,
    compression: 4,
    pros: ['Better than MP3 at same bitrate', 'Hardware accelerated', 'Streaming standard'],
    cons: ['Not as universal as MP3', 'Slightly more complex to encode'],
    browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera'],
    useCases: ['YouTube audio', 'Apple ecosystem', 'Streaming', 'Modern audio'],
  },
  m4a: {
    id: 'm4a',
    label: 'M4A',
    type: 'audio',
    extensions: ['.m4a'],
    mimeType: 'audio/mp4',
    description: 'MPEG-4 Audio — Apple\'s preferred format, typically AAC-encoded. Standard for iTunes and Apple Music.',
    bestFor: ['Apple Devices', 'iTunes', 'Music Library'],
    compatibility: 4,
    quality: 4,
    compression: 4,
    pros: ['AAC quality', 'Apple native', 'Metadata support', 'Streaming-friendly'],
    cons: ['Less universal than MP3', 'Apple-centric ecosystem'],
    browserSupport: ['Safari', 'Chrome', 'Edge'],
    useCases: ['iTunes/Apple Music', 'Apple device playback', 'Podcasts'],
  },
  flac: {
    id: 'flac',
    label: 'FLAC',
    type: 'audio',
    extensions: ['.flac'],
    mimeType: 'audio/flac',
    description: 'Free Lossless Audio Codec — compresses audio without losing any quality. The gold standard for lossless audio.',
    bestFor: ['Audiophile', 'Archiving', 'Lossless Music', 'High Quality'],
    compatibility: 3,
    quality: 5,
    compression: 3,
    pros: ['Lossless quality', 'Free/open', 'Good compression for lossless', 'Metadata support'],
    cons: ['Larger than lossy formats', 'Limited portable device support', 'Not streaming-optimized'],
    browserSupport: ['Chrome', 'Firefox', 'Edge', 'Opera'],
    useCases: ['Music archiving', 'Audiophile listening', 'Lossless distribution'],
  },
};

export const ALL_FORMATS = Object.values(FORMATS);

export function getFormat(id: string): FormatInfo | undefined {
  return FORMATS[id];
}

export function getInputFormats(): FormatInfo[] {
  return ALL_FORMATS.filter((f) => f.type === 'video');
}

export function getOutputFormats(): FormatInfo[] {
  return ALL_FORMATS;
}
