/**
 * Media Studio — Device/Platform Presets
 *
 * Pre-configured encoding profiles for popular platforms and devices.
 */

import type { PresetDefinition } from './types';

export const PRESETS: PresetDefinition[] = [
  {
    id: 'youtube',
    label: 'YouTube',
    description: 'Optimized for YouTube uploads. H.264 video with AAC audio in MP4 container.',
    icon: 'Play',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '8M',
    audioBitrate: '192k',
    crf: 23,
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    description: 'Vertical video optimized for TikTok. 9:16 aspect ratio, H.264 high quality.',
    icon: 'Music',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    width: 1080,
    height: 1920,
    frameRate: 30,
    videoBitrate: '6M',
    audioBitrate: '128k',
  },
  {
    id: 'instagram',
    label: 'Instagram',
    description: 'Optimized for Instagram feed and stories. Square or vertical format with H.264.',
    icon: 'Camera',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    width: 1080,
    height: 1080,
    frameRate: 30,
    videoBitrate: '5M',
    audioBitrate: '128k',
  },
  {
    id: 'facebook',
    label: 'Facebook',
    description: 'Optimized for Facebook video uploads. Standard H.264 with high compatibility.',
    icon: 'MessageCircle',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '4M',
    audioBitrate: '128k',
    crf: 24,
  },
  {
    id: 'telegram',
    label: 'Telegram',
    description: 'Compressed for Telegram sharing. Smaller file size while maintaining good quality.',
    icon: 'Send',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '2M',
    audioBitrate: '96k',
    crf: 28,
  },
  {
    id: 'discord',
    label: 'Discord',
    description: 'Optimized for Discord file sharing. Stays under Discord\'s file size limits.',
    icon: 'MessageSquare',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '3M',
    audioBitrate: '96k',
    crf: 26,
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    description: 'Compressed for WhatsApp sharing. Small file size optimized for mobile messaging.',
    icon: 'Phone',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '1.5M',
    audioBitrate: '64k',
    crf: 30,
  },
  {
    id: 'obs',
    label: 'OBS',
    description: 'Optimized for OBS Studio. High quality recording preset with H.264 or H.265.',
    icon: 'Monitor',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '16M',
    audioBitrate: '256k',
    crf: 18,
  },
  {
    id: 'premiere',
    label: 'Premiere Pro',
    description: 'Editing-friendly preset for Adobe Premiere Pro. High quality for smooth editing.',
    icon: 'Film',
    container: 'mov',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '20M',
    audioBitrate: '320k',
    crf: 16,
  },
  {
    id: 'davinci',
    label: 'DaVinci Resolve',
    description: 'Optimized for DaVinci Resolve. High bitrate for color grading and post-production.',
    icon: 'Clapperboard',
    container: 'mov',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '25M',
    audioBitrate: '320k',
    crf: 15,
  },
  {
    id: 'final-cut',
    label: 'Final Cut Pro',
    description: 'Optimized for Final Cut Pro on macOS. ProRes-compatible high quality preset.',
    icon: 'Apple',
    container: 'mov',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '20M',
    audioBitrate: '256k',
    crf: 16,
  },
  {
    id: 'capcut',
    label: 'CapCut',
    description: 'Optimized for CapCut mobile editing. Good quality with manageable file sizes.',
    icon: 'Scissors',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '8M',
    audioBitrate: '192k',
    crf: 22,
  },
  {
    id: 'android',
    label: 'Android',
    description: 'Optimized for Android devices. H.264 with broad compatibility across Android versions.',
    icon: 'Smartphone',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '4M',
    audioBitrate: '128k',
    crf: 24,
  },
  {
    id: 'iphone',
    label: 'iPhone',
    description: 'Optimized for iPhone playback. HEVC (H.265) for best quality on Apple devices.',
    icon: 'Smartphone',
    container: 'mp4',
    videoCodec: 'h265',
    audioCodec: 'aac',
    videoBitrate: '6M',
    audioBitrate: '128k',
    crf: 22,
  },
  {
    id: 'windows',
    label: 'Windows',
    description: 'Optimized for Windows Media Player and legacy compatibility.',
    icon: 'Monitor',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '5M',
    audioBitrate: '192k',
    crf: 23,
  },
  {
    id: 'macos',
    label: 'macOS',
    description: 'Optimized for macOS QuickTime and Safari. Good balance of quality and compatibility.',
    icon: 'Apple',
    container: 'mp4',
    videoCodec: 'h264',
    audioCodec: 'aac',
    videoBitrate: '6M',
    audioBitrate: '192k',
    crf: 22,
  },
];

export function getPreset(id: string): PresetDefinition | undefined {
  return PRESETS.find((p) => p.id === id);
}

export function getPresetsByContainer(container: string): PresetDefinition[] {
  return PRESETS.filter((p) => p.container === container);
}
