import { describe, expect, it } from 'vitest';

import {
  calculateCheckDigit,
  explainCheckDigit,
  validateCheckDigit,
} from './checkDigit';

/**
 * Every code below is a real, published barcode — not a value produced by this
 * implementation. That matters: the weighting bug these tests were written to
 * catch produced self-consistent nonsense, so a fixture generated by the code
 * itself would have agreed with it.
 *
 * The bug: weights alternate 3, 1, 3, 1 anchored at the RIGHT-hand data digit.
 * Anchoring them at the left is correct only when the data length is odd, so
 * UPC-A (11 data digits) and EAN-8 (7) passed while EAN-13, ISBN-13, ISSN and
 * ISMN (12 each) were wrong about nine times in ten.
 */

const PUBLISHED: ReadonlyArray<[string, string, string, string]> = [
  // [type, data without check digit, expected check digit, what it is]
  ['ean13', '400638133393', '1', 'Ferrero Rocher, 4006381333931'],
  ['isbn13', '978030640615', '7', 'ISBN 978-0-306-40615-7'],
  ['issn', '037761240000', '0', 'ISSN 0377-6123 as EAN-13'],
  ['upca', '03600029145', '2', 'UPC-A 036000291452'],
  ['ean8', '9638507', '4', 'EAN-8 96385074'],
  ['isbn10', '030640615', '2', 'ISBN-10 0306406152'],
];

describe('calculateCheckDigit', () => {
  it.each(PUBLISHED)('%s: %s → %s (%s)', (type, data, expected) => {
    expect(calculateCheckDigit(data, type as never)).toBe(expected);
  });

  it('weights the last data digit by three, not the first', () => {
    // 12 data digits: left-anchored weighting gives 9 here, right-anchored 7.
    expect(calculateCheckDigit('501001440105', 'ean13')).toBe('7');
  });

  it('ignores separators in the input', () => {
    expect(calculateCheckDigit('978-0-306-40615', 'isbn13')).toBe('7');
  });
});

describe('validateCheckDigit', () => {
  it.each(PUBLISHED)('accepts the full code for %s (%s)', (type, data, expected) => {
    const result = validateCheckDigit(data + expected, type as never);

    expect(result.valid).toBe(true);
    expect(result.expected).toBe(expected);
    expect(result.actual).toBe(expected);
  });

  it('rejects a code whose check digit is wrong', () => {
    const result = validateCheckDigit('4006381333939', 'ean13');

    expect(result.valid).toBe(false);
    expect(result.expected).toBe('1');
    expect(result.actual).toBe('9');
  });

  it('does not crash on input that is too short', () => {
    expect(validateCheckDigit('4', 'ean13').valid).toBe(false);
  });
});

describe('explainCheckDigit', () => {
  it('reaches the same digit the calculator does', () => {
    const explanation = explainCheckDigit('4006381333931', 'ean13');

    expect(explanation).not.toBeNull();
    expect(explanation!.checkDigit).toBe('1');
    expect(explanation!.fullCode).toBe('4006381333931');
  });

  it('shows the weights it actually used', () => {
    // The explanation and the calculator shared the same off-by-one weighting
    // before, so a user could not have spotted the error from the steps.
    const explanation = explainCheckDigit('4006381333931', 'ean13');
    const weightStep = explanation!.steps[1];

    expect(weightStep).toContain('3 × 3'); // last data digit is 3, weighted ×3
  });

  it('returns null for symbologies that carry no check digit', () => {
    expect(explainCheckDigit('ABC123', 'code39')).toBeNull();
  });
});
