/**
 * Crypto Wallet Playground — Network Registry.
 *
 * Defines all 22+ supported blockchain networks with their parameters.
 */

import type { Network, NetworkId } from './types';

export const NETWORKS: Record<NetworkId, Network> = {
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    coinType: 0,
    addressFormats: ['legacy', 'segwit', 'native-segwit', 'taproot'],
    hrp: 'bc',
    prefixes: ['00', '05'],
    explorerUrl: 'https://blockstream.info',
    testnetExplorerUrl: 'https://blockstream.info/testnet',
    nativeToken: 'BTC',
    decimals: 8,
    consensus: 'PoW',
    description: 'The original cryptocurrency. Supports P2PKH (Legacy), P2SH (SegWit), bech32 (Native SegWit), and bech32m (Taproot) address formats.',
  },
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    coinType: 60,
    addressFormats: ['eip55'],
    explorerUrl: 'https://etherscan.io',
    testnetExplorerUrl: 'https://sepolia.etherscan.io',
    nativeToken: 'ETH',
    decimals: 18,
    chainId: 1,
    consensus: 'PoS',
    description: 'Smart contract platform. Uses EIP-55 mixed-case checksummed addresses (0x-prefixed hex).',
  },
  'bnb-chain': {
    id: 'bnb-chain',
    name: 'BNB Chain',
    symbol: 'BNB',
    coinType: 714,
    addressFormats: ['eip55'],
    explorerUrl: 'https://bscscan.com',
    testnetExplorerUrl: 'https://testnet.bscscan.com',
    nativeToken: 'BNB',
    decimals: 18,
    chainId: 56,
    consensus: 'PoSA',
    description: 'Blockchain for decentralized applications. EVM-compatible with Ethereum-style addresses.',
  },
  polygon: {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'MATIC',
    coinType: 966,
    addressFormats: ['eip55'],
    explorerUrl: 'https://polygonscan.com',
    testnetExplorerUrl: 'https://amoy.polygonscan.com',
    nativeToken: 'MATIC',
    decimals: 18,
    chainId: 137,
    consensus: 'PoS',
    description: 'Ethereum scaling platform. EVM-compatible with Ethereum-style addresses.',
  },
  avalanche: {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'AVAX',
    coinType: 9000,
    addressFormats: ['eip55'],
    explorerUrl: 'https://snowtrace.io',
    nativeToken: 'AVAX',
    decimals: 18,
    chainId: 43114,
    consensus: 'Snowman',
    description: 'High-throughput blockchain platform. C-Chain uses EVM-compatible addresses.',
  },
  arbitrum: {
    id: 'arbitrum',
    name: 'Arbitrum',
    symbol: 'ARB',
    coinType: 9001,
    addressFormats: ['eip55'],
    explorerUrl: 'https://arbiscan.io',
    nativeToken: 'ETH',
    decimals: 18,
    chainId: 42161,
    consensus: 'Rollup',
    description: 'Ethereum L2 rollup. EVM-compatible with Ethereum-style addresses.',
  },
  optimism: {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'OP',
    coinType: 9014,
    addressFormats: ['eip55'],
    explorerUrl: 'https://optimistic.etherscan.io',
    nativeToken: 'ETH',
    decimals: 18,
    chainId: 10,
    consensus: 'Rollup',
    description: 'Ethereum L2 optimistic rollup. EVM-compatible with Ethereum-style addresses.',
  },
  base: {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    coinType: 8453,
    addressFormats: ['eip55'],
    explorerUrl: 'https://basescan.org',
    nativeToken: 'ETH',
    decimals: 18,
    chainId: 8453,
    consensus: 'Rollup',
    description: 'Coinbase L2 rollup. EVM-compatible with Ethereum-style addresses.',
  },
  solana: {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    coinType: 501,
    addressFormats: ['base58'],
    explorerUrl: 'https://explorer.solana.com',
    testnetExplorerUrl: 'https://explorer.solana.com/?cluster=testnet',
    nativeToken: 'SOL',
    decimals: 9,
    consensus: 'PoH+PoS',
    description: 'High-performance blockchain. Uses Base58-encoded 32-byte public keys.',
  },
  tron: {
    id: 'tron',
    name: 'TRON',
    symbol: 'TRX',
    coinType: 195,
    addressFormats: ['base58'],
    explorerUrl: 'https://tronscan.org',
    nativeToken: 'TRX',
    decimals: 6,
    consensus: 'DPoS',
    description: 'Decentralized entertainment and content platform. Uses Base58-check addresses.',
  },
  litecoin: {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'LTC',
    coinType: 2,
    addressFormats: ['legacy', 'segwit', 'native-segwit'],
    hrp: 'ltc',
    prefixes: ['30', '05', '32'],
    explorerUrl: 'https://litecoinblockexplorer.net',
    nativeToken: 'LTC',
    decimals: 8,
    consensus: 'PoW (Scrypt)',
    description: 'Peer-to-peer cryptocurrency based on Scrypt PoW. Supports Legacy (L), SegWit (M), and bech32 (ltc1) formats.',
  },
  dogecoin: {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    coinType: 3,
    addressFormats: ['legacy'],
    prefixes: ['1e', '16'],
    explorerUrl: 'https://dogechain.info',
    nativeToken: 'DOGE',
    decimals: 8,
    consensus: 'PoW (Scrypt)',
    description: 'Fun, meme-inspired cryptocurrency. Uses Legacy format addresses (D-prefix).',
  },
  'bitcoin-cash': {
    id: 'bitcoin-cash',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    coinType: 145,
    addressFormats: ['legacy'],
    prefixes: ['00', '05'],
    explorerUrl: 'https://blockchair.com/bitcoin-cash',
    nativeToken: 'BCH',
    decimals: 8,
    consensus: 'PoW',
    description: 'Bitcoin fork with larger blocks. Uses Legacy format addresses with cashaddr prefix.',
  },
  monero: {
    id: 'monero',
    name: 'Monero',
    symbol: 'XMR',
    coinType: 128,
    addressFormats: ['base58'],
    explorerUrl: 'https://explorer.monero.world',
    nativeToken: 'XMR',
    decimals: 12,
    consensus: 'PoW (RandomX)',
    description: 'Privacy-focused cryptocurrency. Uses stealth addresses with Base58 encoding. (Reference only — no generation.)',
  },
  ripple: {
    id: 'ripple',
    name: 'Ripple',
    symbol: 'XRP',
    coinType: 144,
    addressFormats: ['base58'],
    prefixes: ['00'],
    explorerUrl: 'https://xrpscan.com',
    testnetExplorerUrl: 'https://testnet.xrpscan.com',
    nativeToken: 'XRP',
    decimals: 6,
    consensus: 'XRP Ledger Consensus',
    description: 'Digital payment protocol. Uses Base58-encoded addresses starting with "r".',
  },
  cardano: {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ADA',
    coinType: 1815,
    addressFormats: ['bech32'],
    hrp: 'addr',
    explorerUrl: 'https://cardanoscan.io',
    nativeToken: 'ADA',
    decimals: 6,
    consensus: 'PoS (Ouroboros)',
    description: 'Proof-of-stake blockchain platform. Uses bech32-encoded addresses.',
  },
  polkadot: {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    coinType: 354,
    addressFormats: ['base58'],
    explorerUrl: 'https://polkadot.subscan.io',
    nativeToken: 'DOT',
    decimals: 10,
    consensus: 'NPoS',
    description: 'Multi-chain interoperability protocol. Uses Base58-encoded SS58 addresses.',
  },
  cosmos: {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'ATOM',
    coinType: 118,
    addressFormats: ['bech32'],
    hrp: 'cosmos',
    explorerUrl: 'https://mintscan.io/cosmos',
    nativeToken: 'ATOM',
    decimals: 6,
    consensus: 'Tendermint BFT',
    description: 'Interoperable blockchain ecosystem. Uses bech32-encoded addresses with "cosmos" prefix.',
  },
  near: {
    id: 'near',
    name: 'NEAR Protocol',
    symbol: 'NEAR',
    coinType: 397,
    addressFormats: ['base58'],
    explorerUrl: 'https://nearscan.io',
    nativeToken: 'NEAR',
    decimals: 24,
    consensus: 'Doomslug',
    description: 'Developer-friendly sharded blockchain. Uses Base58-encoded addresses.',
  },
  ton: {
    id: 'ton',
    name: 'TON',
    symbol: 'TON',
    coinType: 607,
    addressFormats: ['base58'],
    explorerUrl: 'https://tonscan.org',
    nativeToken: 'TON',
    decimals: 9,
    consensus: 'PoS',
    description: 'The Open Network. Multi-blockchain platform with unique address format.',
  },
};

export const ALL_NETWORKS = Object.values(NETWORKS);

export function getNetwork(id: NetworkId): Network {
  return NETWORKS[id];
}

export function getNetworkByCoinType(coinType: number): Network | undefined {
  return ALL_NETWORKS.find((n) => n.coinType === coinType);
}

export function getNetworksByFormat(format: string): Network[] {
  return ALL_NETWORKS.filter((n) => n.addressFormats.some((f) => f === format));
}

export const NETWORK_IDS = Object.keys(NETWORKS) as NetworkId[];

export const NETWORK_NAMES: Record<NetworkId, string> = Object.fromEntries(
  ALL_NETWORKS.map((n) => [n.id, n.name]),
) as Record<NetworkId, string>;
