/**
 * Crypto Wallet Playground — Developer Playground.
 *
 * Exports wallet structures in various programming languages.
 */

import type { WalletResult, ExportTemplate } from './types';

export interface ExportOptions {
  wallet: WalletResult;
  includePrivateKey: boolean;
}

function toJSON(wallet: WalletResult, includePrivateKey: boolean): string {
  const obj: Record<string, unknown> = {
    network: wallet.network,
    address: wallet.address,
    format: wallet.format,
    publicKey: wallet.publicKey,
    derivationPath: wallet.derivationPath,
  };
  if (includePrivateKey && wallet.privateKey) {
    obj.privateKey = wallet.privateKey;
  }
  if (wallet.mnemonic) {
    obj.mnemonic = wallet.mnemonic;
  }
  return JSON.stringify(obj, null, 2);
}

function toTypeScript(wallet: WalletResult, includePrivateKey: boolean): string {
  const lines: string[] = [
    '// Wallet generated by Crypto Wallet Playground',
    '// WARNING: For testing/educational purposes only',
    '',
    'interface Wallet {',
    '  network: string;',
    '  address: string;',
    '  format: string;',
    '  publicKey: string;',
    '  derivationPath: string;',
    includePrivateKey ? '  privateKey: string;' : '  // privateKey: string; // omitted',
    wallet.mnemonic ? '  mnemonic: string;' : '',
    '}',
    '',
    'const wallet: Wallet = {',
    `  network: '${wallet.network}',`,
    `  address: '${wallet.address}',`,
    `  format: '${wallet.format}',`,
    `  publicKey: '${wallet.publicKey}',`,
    `  derivationPath: '${wallet.derivationPath}',`,
    includePrivateKey && wallet.privateKey ? `  privateKey: '${wallet.privateKey}',` : '',
    wallet.mnemonic ? `  mnemonic: '${wallet.mnemonic}',` : '',
    '};',
    '',
    'export default wallet;',
  ];
  return lines.filter(Boolean).join('\n');
}

function toSolidity(wallet: WalletResult, _includePrivateKey: boolean): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title Wallet Playground — Generated Address
 * @notice WARNING: For testing/educational purposes only
 */
contract WalletInfo {
    string public constant NETWORK = "${wallet.network}";
    string public constant ADDRESS = "${wallet.address}";
    string public constant FORMAT = "${wallet.format}";
    string public constant PUBLIC_KEY = "${wallet.publicKey}";
    string public constant DERIVATION_PATH = "${wallet.derivationPath}";
}
`;
}

function toRust(wallet: WalletResult, includePrivateKey: boolean): string {
  const fields: string[] = [
    `network: "${wallet.network}".to_string(),`,
    `address: "${wallet.address}".to_string(),`,
    `format: "${wallet.format}".to_string(),`,
    `public_key: "${wallet.publicKey}".to_string(),`,
    `derivation_path: "${wallet.derivationPath}".to_string(),`,
  ];
  if (includePrivateKey && wallet.privateKey) {
    fields.push(`private_key: Some("${wallet.privateKey}".to_string()),`);
  }
  const fieldsStr = fields.map((f) => `        ${f}`).join('\n');

  return `// Wallet generated by Crypto Wallet Playground
// WARNING: For testing/educational purposes only

struct Wallet {
    network: String,
    address: String,
    format: String,
    public_key: String,
    derivation_path: String,
    private_key: Option<String>,
}

fn get_wallet() -> Wallet {
    Wallet {
${fieldsStr}
    }
}
`;
}

function toGo(wallet: WalletResult, includePrivateKey: boolean): string {
  const fields: string[] = [
    `Network: "${wallet.network}",`,
    `Address: "${wallet.address}",`,
    `Format: "${wallet.format}",`,
    `PublicKey: "${wallet.publicKey}",`,
    `DerivationPath: "${wallet.derivationPath}",`,
  ];
  if (includePrivateKey && wallet.privateKey) {
    fields.push(`PrivateKey: "${wallet.privateKey}",`);
  }
  const fieldsStr = fields.map((f) => `\t${f}`).join('\n');

  return `// Wallet generated by Crypto Wallet Playground
// WARNING: For testing/educational purposes only

package main

type Wallet struct {
    Network        string
    Address        string
    Format         string
    PublicKey      string
    DerivationPath string
    PrivateKey     string
}

var wallet = Wallet{
${fieldsStr}
}
`;
}

function toPython(wallet: WalletResult, includePrivateKey: string | boolean): string {
  const isInc = typeof includePrivateKey === 'boolean' ? includePrivateKey : false;
  const fields: string[] = [
    `    "network": "${wallet.network}",`,
    `    "address": "${wallet.address}",`,
    `    "format": "${wallet.format}",`,
    `    "public_key": "${wallet.publicKey}",`,
    `    "derivation_path": "${wallet.derivationPath}",`,
  ];
  if (isInc && wallet.privateKey) {
    fields.push(`    "private_key": "${wallet.privateKey}",`);
  }
  const fieldsStr = fields.map((f) => `    ${f}`).join('\n');

  return `# Wallet generated by Crypto Wallet Playground
# WARNING: For testing/educational purposes only

wallet = {
${fieldsStr}
}
`;
}

function toJava(wallet: WalletResult, _includePrivateKey: boolean): string {
  return `// Wallet generated by Crypto Wallet Playground
// WARNING: For testing/educational purposes only

public class Wallet {
    public static final String NETWORK = "${wallet.network}";
    public static final String ADDRESS = "${wallet.address}";
    public static final String FORMAT = "${wallet.format}";
    public static final String PUBLIC_KEY = "${wallet.publicKey}";
    public static final String DERIVATION_PATH = "${wallet.derivationPath}";

    private Wallet() {}
}
`;
}

function toKotlin(wallet: WalletResult, _includePrivateKey: boolean): string {
  return `// Wallet generated by Crypto Wallet Playground
// WARNING: For testing/educational purposes only

object Wallet {
    const val NETWORK = "${wallet.network}"
    const val ADDRESS = "${wallet.address}"
    const val FORMAT = "${wallet.format}"
    const val PUBLIC_KEY = "${wallet.publicKey}"
    const val DERIVATION_PATH = "${wallet.derivationPath}"
}
`;
}

function toSwift(wallet: WalletResult, _includePrivateKey: boolean): string {
  return `// Wallet generated by Crypto Wallet Playground
// WARNING: For testing/educational purposes only

struct Wallet {
    let network = "${wallet.network}"
    let address = "${wallet.address}"
    let format = "${wallet.format}"
    let publicKey = "${wallet.publicKey}"
    let derivationPath = "${wallet.derivationPath}"
}

let wallet = Wallet()
`;
}

export function exportWallet(
  options: ExportOptions,
  language: string,
): ExportTemplate {
  const { wallet, includePrivateKey } = options;
  let code = '';

  switch (language) {
    case 'json':
      code = toJSON(wallet, includePrivateKey);
      break;
    case 'typescript':
      code = toTypeScript(wallet, includePrivateKey);
      break;
    case 'solidity':
      code = toSolidity(wallet, includePrivateKey);
      break;
    case 'rust':
      code = toRust(wallet, includePrivateKey);
      break;
    case 'go':
      code = toGo(wallet, includePrivateKey);
      break;
    case 'python':
      code = toPython(wallet, includePrivateKey);
      break;
    case 'java':
      code = toJava(wallet, includePrivateKey);
      break;
    case 'kotlin':
      code = toKotlin(wallet, includePrivateKey);
      break;
    case 'swift':
      code = toSwift(wallet, includePrivateKey);
      break;
    default:
      code = toJSON(wallet, includePrivateKey);
  }

  return {
    language,
    code,
  };
}

export const SUPPORTED_LANGUAGES = [
  'json',
  'typescript',
  'solidity',
  'rust',
  'go',
  'python',
  'java',
  'kotlin',
  'swift',
] as const;
